version: "3.5"
services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    command:
      - 'redis-server'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
    volumes:
      - ./redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
  laravel-app:
      build: 
        context: .
        dockerfile: ./docker/laravel-app/Dockerfile
      container_name: laravel-app
      working_dir: /var/www
      # command: "sh ./deploy.sh"
      environment:
        APP_NAME: "CS-TASK-2"
        REDIS_HOST: "redis"
        REDIS_PASSWORD: "null"
        REDIS_PORT: "6379"
        REDIS_DB: "0"
      depends_on:
        - redis
      networks:
        - app-network
  nginx:
      image: nginx:latest
      container_name: nginx
      working_dir: /var/www
      depends_on:
        - redis
        - laravel-app
      networks:
        - app-network
      ports:
          - "8080:80"
      volumes:
          - ./src:/var/www
          - ./docker/nginx/conf.d/fpm.conf:/etc/nginx/conf.d/default.conf
networks:
  app-network:
    driver: bridge